decay: 0.9
depth: 2
dropout: 0.0
ema: false
embed_dim: 256
embed_mode: linear
embed_strat: sum
heads: 4
lr: 0.0001
num_channels: 321
patch_len: 8
residual: false
seq_len: 336
target_seq_size: 96
use_4782: true
